name: Build All Platforms

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        pip install flet
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.2'
    - name: Install Linux dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev
    - name: Build Linux
      run: |
        flet build linux -v --build-number $BUILD_NUMBER --build-version $BUILD_VERSION
    - uses: actions/upload-artifact@v4
      with:
        name: linux-app
        path: build/linux/

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        pip install flet
        if (Test-Path requirements.txt) { pip install -r requirements.txt }
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.2'
    - name: Build Windows
      run: |
        flet build windows -v --build-number $env:BUILD_NUMBER --build-version $env:BUILD_VERSION
    - uses: actions/upload-artifact@v4
      with:
        name: windows-app
        path: build/windows/

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        pip install flet
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.2'
    - name: Build macOS
      run: |
        flet build macos -v --build-number $BUILD_NUMBER --build-version $BUILD_VERSION
    - uses: actions/upload-artifact@v4
      with:
        name: macos-app
        path: build/macos/

  build-android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        pip install flet
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.2'
    - name: Setup JDK 17  # ✅ التغيير هنا
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    - name: Build APK
      run: |
        flet build apk -v --build-number $BUILD_NUMBER --build-version $BUILD_VERSION
    - uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: build/apk/

  build-web:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        pip install flet
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.2'
    - name: Build Web
      run: |
        flet build web -v
    - uses: actions/upload-artifact@v4
      with:
        name: web-app
        path: build/web/
