name: Build Flet Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # يسمح بالتشغيل اليدوي

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Flet
      run: |
        python -m pip install --upgrade pip
        pip install flet
        
    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Build APK
      run: |
        flet build apk --include-packages "[]" --name "MyFletApp" --description "My Flet Application"
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: flet-android-apk
        path: build/apk/*.apk
        retention-days: 30
        
    - name: Upload to GitHub Releases
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: build/apk/*.apk
