name: All Builds (Linux, macOS, Windows, Android, IPA, APK, AAB)

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.12
  FLUTTER_VERSION: 3.29.2  # إصدار مستقر ومتوفر

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet  # ⬅️ ضروري!
        pip install -r requirements.txt

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        cache: true

    - name: Install Linux dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
          clang \
          cmake \
          ninja-build \
          pkg-config \
          libgtk-3-dev \
          liblzma-dev \
          libstdc++-12-dev \
          libsecret-1-dev \
          libjsoncpp-dev

    - name: Verify environment
      run: |
        flutter --version
        flet --version
        flutter doctor -v

    - name: Flet Build Linux
      run: |
        flutter config --no-analytics 
        flet build linux --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION

    - name: Upload Linux Artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-app
        path: build/linux
        if-no-files-found: ignore

  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet
        pip install -r requirements.txt

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        cache: true

    - name: Flet Build Windows
      shell: pwsh
      run: |
        flutter config --no-analytics
        flet build windows --build-number=$env:BUILD_NUMBER --build-version=$env:BUILD_VERSION

    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-app
        path: build/windows
        if-no-files-found: ignore

  build-android-apk:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet
        pip install -r requirements.txt

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        cache: true

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Accept Android licenses
      run: |
        yes | sdkmanager --licenses || true
        flutter doctor --android-licenses --yes

    - name: Verify Android setup
      run: flutter doctor -v

    - name: Flet Build APK
      run: |
        flutter config --no-analytics
        flet build apk --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: build/apk
        if-no-files-found: ignore

  build-android-aab:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet
        pip install -r requirements.txt

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        cache: true

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Accept Android licenses
      run: |
        yes | sdkmanager --licenses || true
        flutter doctor --android-licenses --yes

    - name: Flet Build AAB
      run: |
        flutter config --no-analytics
        flet build aab --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION

    - name: Upload AAB Artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-aab
        path: build/aab
        if-no-files-found: ignore

  build-web:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet
        pip install -r requirements.txt

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        cache: true

    - name: Flet Build Web
      run: |
        flutter config --no-analytics
        flet build web --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION

    - name: Upload Web Artifact
      uses: actions/upload-artifact@v4
      with:
        name: web-app
        path: build/web
        if-no-files-found: ignore

  # إزالة macOS و iOS مؤقتاً لأنها تحتاج شهادات تطوير
