name: Android Builds (Flet APK & AAB Fixed)

on:
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.12.2
  FLUTTER_VERSION: 3.22.2

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Setup Java JDK
      uses: actions/setup-java@v4.2.1
      with:
        distribution: 'temurin'
        java-version: '17'

    # 🧩 إعداد Android SDK كامل
    - name: Setup Android SDK
      run: |
        sudo apt-get update -y
        sudo apt-get install -y wget unzip
        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
        mkdir -p $HOME/android-sdk/cmdline-tools
        unzip -q cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools
        mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
        echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH
        sdkmanager --version
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

    - name: Accept Android Licenses
      run: yes | flutter doctor --android-licenses

    - name: Verify Flutter Doctor
      run: flutter doctor -v

    # ✅ بناء APK
    - name: Build APK
      run: |
        flutter config --no-analytics
        flet build apk --verbose --build-number=1 --build-version=1.0.0

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: apk-build
        path: build/apk
        if-no-files-found: warn
        overwrite: false

    # ✅ بناء AAB
    - name: Build AAB
      run: |
        flutter config --no-analytics
        flet build aab --verbose --build-number=1 --build-version=1.0.0

    - name: Upload AAB Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: aab-build
        path: build/aab
        if-no-files-found: warn
        overwrite: false
