name: Build Android (Flet - APK & AAB)

on:
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.12.2
  FLUTTER_VERSION: 3.22.2
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python + Flet
      run: |
        python -m pip install --upgrade pip
        pip install flet flutter-wrapper

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      run: |
        sudo apt-get update -y
        sudo apt-get install -y wget unzip
        mkdir -p $HOME/android-sdk
        cd $HOME/android-sdk
        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O tools.zip
        unzip tools.zip -d cmdline-tools
        mkdir -p cmdline-tools/latest
        mv cmdline-tools/* cmdline-tools/latest/ || true
        echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH
        yes | sdkmanager --sdk_root=$HOME/android-sdk --licenses
        sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "platforms;android-34" "build-tools;34.0.0"

    - name: Accept Android Licenses
      run: yes | flutter doctor --android-licenses

    - name: Check Flutter & Flet
      run: |
        flutter --version
        flet --version
        flutter doctor -v

    - name: Build APK
      run: |
        flet build apk --verbose --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: apk-build
        path: build/apk

    - name: Build AAB
      run: |
        flet build aab --verbose --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION

    - name: Upload AAB
      uses: actions/upload-artifact@v4
      with:
        name: aab-build
        path: build/aab
