name: Build Flet Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Flet
      run: |
        pip install flet
        
    - name: Setup Flutter 3.35.1 (latest stable)
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.1'
        channel: 'stable'
        
    - name: Setup Java JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Accept Android licenses
      run: |
        flutter precache --android
        yes | flutter doctor --android-licenses || true
        yes | sdkmanager --licenses || true
        flutter doctor  # Verify all ✓
        
    - name: Create Flet config file
      run: |
        cat > flet.json << EOF
        {
          "name": "MyFletApp",
          "description": "My Flet Application",
          "version": "1.0.0",
          "android": {
            "package": "com.example.myfletapp",
            "min_sdk": 21,
            "target_sdk": 34
          }
        }
        EOF
        
    - name: Build APK
      run: |
        flutter config --no-analytics
        flet build apk --verbose
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: flet-android-apk
        path: build/apk/*.apk
        if-no-files-found: error
